package cn.com.syzg.model;

import java.io.Serializable;

public class Cart implements Serializable{
    private static final long serialVersionUID = -3352184760508469630L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goodsId
     *
     * @mbg.generated
     */
    private Integer goodsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.emplyNo
     *
     * @mbg.generated
     */
    private String emplyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart.goodsList
     *
     * @mbg.generated
     */
    private String goodslist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.id
     *
     * @return the value of cart.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.id
     *
     * @param id the value for cart.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.goodsId
     *
     * @return the value of cart.goodsId
     *
     * @mbg.generated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.goodsId
     *
     * @param goodsid the value for cart.goodsId
     *
     * @mbg.generated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.emplyNo
     *
     * @return the value of cart.emplyNo
     *
     * @mbg.generated
     */
    public String getEmplyno() {
        return emplyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.emplyNo
     *
     * @param emplyno the value for cart.emplyNo
     *
     * @mbg.generated
     */
    public void setEmplyno(String emplyno) {
        this.emplyno = emplyno == null ? null : emplyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart.goodsList
     *
     * @return the value of cart.goodsList
     *
     * @mbg.generated
     */
    public String getGoodslist() {
        return goodslist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart.goodsList
     *
     * @param goodslist the value for cart.goodsList
     *
     * @mbg.generated
     */
    public void setGoodslist(String goodslist) {
        this.goodslist = goodslist == null ? null : goodslist.trim();
    }

    public Cart(Integer id, Integer goodsid, String emplyno, String goodslist) {
        this.id = id;
        this.goodsid = goodsid;
        this.emplyno = emplyno;
        this.goodslist = goodslist;
    }

    public Cart(Integer goodsid, String emplyno, String goodslist) {
        this.goodsid = goodsid;
        this.emplyno = emplyno;
        this.goodslist = goodslist;
    }

    public Cart() {
    }

    @Override
    public String toString() {
        return "Cart{" +
                "id=" + id +
                ", goodsid=" + goodsid +
                ", emplyno='" + emplyno + '\'' +
                ", goodslist='" + goodslist + '\'' +
                '}';
    }
}