package cn.com.syzg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Emply implements Serializable {
    private static final long serialVersionUID = -5097933007857738017L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emply.emplyNo
     *
     * @mbg.generated
     */
    private String emplyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emply.emplyName
     *
     * @mbg.generated
     */
    private String emplyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emply.jobNo
     *
     * @mbg.generated
     */
    private String jobno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emply.birth
     *
     * @mbg.generated
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emply.mobile
     *
     * @mbg.generated
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emply.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emply.deptNo
     *
     * @mbg.generated
     */
    private String deptno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emply.emplyNo
     *
     * @return the value of emply.emplyNo
     *
     * @mbg.generated
     */
    public String getEmplyno() {
        return emplyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emply.emplyNo
     *
     * @param emplyno the value for emply.emplyNo
     *
     * @mbg.generated
     */
    public void setEmplyno(String emplyno) {
        this.emplyno = emplyno == null ? null : emplyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emply.emplyName
     *
     * @return the value of emply.emplyName
     *
     * @mbg.generated
     */
    public String getEmplyname() {
        return emplyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emply.emplyName
     *
     * @param emplyname the value for emply.emplyName
     *
     * @mbg.generated
     */
    public void setEmplyname(String emplyname) {
        this.emplyname = emplyname == null ? null : emplyname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emply.jobNo
     *
     * @return the value of emply.jobNo
     *
     * @mbg.generated
     */
    public String getJobno() {
        return jobno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emply.jobNo
     *
     * @param jobno the value for emply.jobNo
     *
     * @mbg.generated
     */
    public void setJobno(String jobno) {
        this.jobno = jobno == null ? null : jobno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emply.birth
     *
     * @return the value of emply.birth
     *
     * @mbg.generated
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emply.birth
     *
     * @param birth the value for emply.birth
     *
     * @mbg.generated
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emply.mobile
     *
     * @return the value of emply.mobile
     *
     * @mbg.generated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emply.mobile
     *
     * @param mobile the value for emply.mobile
     *
     * @mbg.generated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emply.level
     *
     * @return the value of emply.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emply.level
     *
     * @param level the value for emply.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emply.deptNo
     *
     * @return the value of emply.deptNo
     *
     * @mbg.generated
     */
    public String getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emply.deptNo
     *
     * @param deptno the value for emply.deptNo
     *
     * @mbg.generated
     */
    public void setDeptno(String deptno) {
        this.deptno = deptno == null ? null : deptno.trim();
    }

    private BigDecimal subsidyMoney;

    private Date subsidyTerm;

    private BigDecimal ausedMoney;

    public BigDecimal getSubsidyMoney() {
        return subsidyMoney;
    }

    public void setSubsidyMoney(BigDecimal subsidyMoney) {
        this.subsidyMoney = subsidyMoney;
    }

    public Date getSubsidyTerm() {
        return subsidyTerm;
    }

    public void setSubsidyTerm(Date subsidyTerm) {
        this.subsidyTerm = subsidyTerm;
    }

    public BigDecimal getAusedMoney() {
        return ausedMoney;
    }

    public void setAusedMoney(BigDecimal ausedMoney) {
        this.ausedMoney = ausedMoney;
    }

    public Emply(String emplyno, String emplyname, String jobno, Date birth, String mobile, Integer level, String deptno, BigDecimal subsidyMoney, Date subsidyTerm, BigDecimal ausedMoney) {
        this.emplyno = emplyno;
        this.emplyname = emplyname;
        this.jobno = jobno;
        this.birth = birth;
        this.mobile = mobile;
        this.level = level;
        this.deptno = deptno;
        this.subsidyMoney = subsidyMoney;
        this.subsidyTerm = subsidyTerm;
        this.ausedMoney = ausedMoney;
    }

    public Emply(String emplyname, String jobno, Date birth, String mobile, Integer level, String deptno, BigDecimal subsidyMoney, Date subsidyTerm, BigDecimal ausedMoney) {
        this.emplyname = emplyname;
        this.jobno = jobno;
        this.birth = birth;
        this.mobile = mobile;
        this.level = level;
        this.deptno = deptno;
        this.subsidyMoney = subsidyMoney;
        this.subsidyTerm = subsidyTerm;
        this.ausedMoney = ausedMoney;
    }

    public Emply(String emplyno, BigDecimal ausedMoney) {
        this.emplyno = emplyno;
        this.ausedMoney = ausedMoney;
    }

    public Emply() {
    }

    @Override
    public String toString() {
        return "Emply{" +
                "emplyno='" + emplyno + '\'' +
                ", emplyname='" + emplyname + '\'' +
                ", jobno='" + jobno + '\'' +
                ", birth=" + birth +
                ", mobile='" + mobile + '\'' +
                ", level=" + level +
                ", deptno='" + deptno + '\'' +
                ", subsidyMoney=" + subsidyMoney +
                ", subsidyTerm=" + subsidyTerm +
                ", ausedMoney=" + ausedMoney +
                '}';
    }
}