package cn.com.syzg.model;

import java.io.Serializable;

public class Order implements Serializable {
    private static final long serialVersionUID = 3815903775460416015L;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.emplyNo
     *
     * @mbg.generated
     */
    private String emplyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goosList
     *
     * @mbg.generated
     */
    private String gooslist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.emplyNo
     *
     * @return the value of order.emplyNo
     *
     * @mbg.generated
     */
    public String getEmplyno() {
        return emplyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.emplyNo
     *
     * @param emplyno the value for order.emplyNo
     *
     * @mbg.generated
     */
    public void setEmplyno(String emplyno) {
        this.emplyno = emplyno == null ? null : emplyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goosList
     *
     * @return the value of order.goosList
     *
     * @mbg.generated
     */
    public String getGooslist() {
        return gooslist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goosList
     *
     * @param gooslist the value for order.goosList
     *
     * @mbg.generated
     */
    public void setGooslist(String gooslist) {
        this.gooslist = gooslist == null ? null : gooslist.trim();
    }

    public Order(Integer id, String emplyno, String gooslist) {
        this.id = id;
        this.emplyno = emplyno;
        this.gooslist = gooslist;
    }

    public Order(String emplyno, String gooslist) {
        this.emplyno = emplyno;
        this.gooslist = gooslist;
    }

    public Order() {
    }

    @Override
    public String toString() {
        return "Order{" +
                "id=" + id +
                ", emplyno='" + emplyno + '\'' +
                ", gooslist='" + gooslist + '\'' +
                '}';
    }
}