package cn.com.syzg.model;

import java.io.Serializable;

public class Orders implements Serializable {
    private static final long serialVersionUID = 3815903775460416015L;

    private Goods goods;

    public Goods getGoods() {
        return goods;
    }

    public void setGoods(Goods goods) {
        this.goods = goods;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.emplyNo
     *
     * @mbg.generated
     */
    private String emplyno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goosList
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.emplyNo
     *
     * @return the value of order.emplyNo
     *
     * @mbg.generated
     */
    public String getEmplyno() {
        return emplyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.emplyNo
     *
     * @param emplyno the value for order.emplyNo
     *
     * @mbg.generated
     */
    public void setEmplyno(String emplyno) {
        this.emplyno = emplyno == null ? null : emplyno.trim();
    }

    private Integer count;

    private Integer goodsId;

    public Orders(Integer id, String emplyno, Integer count, Integer goodsId) {
        this.id = id;
        this.emplyno = emplyno;
        this.count = count;
        this.goodsId = goodsId;
    }

    public Orders(String emplyno, Integer count, Integer goodsId) {
        this.emplyno = emplyno;
        this.count = count;
        this.goodsId = goodsId;
    }

    public Orders() {
    }



}