package cn.com.syzg.repository;

import cn.com.syzg.model.Cart;
import io.lettuce.core.dynamic.annotation.Param;

import java.util.List;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Cart record);

    List<Cart> selectByEmplyNo(String emplyNo);

    boolean updateGoodsList(Cart cart);

    Cart selectCartbyEmplyNoAndGoodsId(@Param("emplyNo")String emplyNo,@Param("goodsId")Integer goodsId);

    boolean deletebatchbyCart(List<String> list);
}