package cn.com.syzg.repository;

import cn.com.syzg.model.Cart;
import cn.com.syzg.model.Orders;
import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int insert(Orders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    List<Orders> selectAll();

    int insertBatchOrder(List<Orders> list);
}